Lly
PSY3650J-International-Students/dishdiplomat-www pull request #3
Opened 2023-06-25 16:45 UTC by FS-LLY

2023-06-26 06:34 UTC, Gorgeous-Patrick commented on src/store/canteens/Canteen4.ts
> +  name: 'Canteen2',
Canteen 4

2023-06-26 06:34 UTC, Gorgeous-Patrick commented on src/components/Dialog.vue
> +              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
?

2023-06-26 16:12 UTC, FS-LLY commented on src/components/Dialog.vue
> +              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
这是人家的模板，我把它截了一段放到WindowCard了。现在可以点card打开dipole,不过只有固定内容，具体的菜品内容不知道怎么绑到每个窗口

2023-06-27 02:19 UTC, Gorgeous-Patrick commented
Note: 自动测试（yarn build）失败了

2023-06-27 02:19 UTC, Gorgeous-Patrick submitted a review, later dismissed

2023-06-27 02:39 UTC, Gorgeous-Patrick commented on src/components/WindowCard.vue
> +              Hi,我是颠佬
Say. Under construction

2023-06-27 02:39 UTC, Gorgeous-Patrick commented on src/components/WindowCard.vue
> +      event.stopPropagation()
I think this is useless

2023-06-27 02:39 UTC, Gorgeous-Patrick commented on src/components/Dialog.vue
> +              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
我感觉可以不用单独拆成一个component，不需要的文件就删掉吧。

2023-06-28 08:35 UTC, Gorgeous-Patrick requested changes

2023-06-28 08:35 UTC, Gorgeous-Patrick commented on src/components/WindowCard.vue
> +      event.stopPropagation()
这句话不知道哪来的。。event都没有定义。删掉吧

2023-06-28 08:35 UTC, Gorgeous-Patrick commented on src/components/WindowCard.vue
> +                      :src="dish.cover_picture"
这个你可能需要用个v-if

2023-06-28 08:40 UTC, Gorgeous-Patrick commented on src/components/WindowCard.vue
> +                      :src="dish.cover_picture"
这个的话你可能需要一些强制类型转换。
![image](https://github.com/PSY3650J-International-Students/dishdiplomat-www/assets/33488623/1e024385-6075-48ff-8933-c090dab9c2ca)

2023-06-28 08:42 UTC, Gorgeous-Patrick commented on src/components/WindowCard.vue
> +                      :src="dish.cover_picture"
就你可以选择在ts里面把string | null 转换为string赋值给一个ref，然后在template里面搞个v-if，判断一下源是不是null，如果是的话就跳过那个img，不是的化就用刚刚创建的ref

2023-06-28 08:50 UTC, Gorgeous-Patrick approved these changes
LGTM!!

2023-06-28 08:50 UTC, merged